# Generated by Django 5.2.1 on 2025-05-27 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Irktech', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ventName', models.TextField(verbose_name='Название заготовки')),
                ('picture', models.TimeField(verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Заготовка',
                'verbose_name_plural': 'Заготовки',
            },
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
