# Generated by Django 5.2.1 on 2025-05-27 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Irktech', '0002_vent_delete_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vent',
            name='picture',
            field=models.TextField(verbose_name='Изображение'),
        ),
    ]
