# Generated by Django 5.2.1 on 2025-05-27 03:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Irktech', '0003_alter_vent_picture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderNumber', models.TextField(verbose_name='Номер заказа')),
                ('amount', models.TextField(verbose_name='Количество')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('date', models.DateField(verbose_name='Дата')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param', models.TextField(verbose_name='Характеристики')),
                ('ventName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Irktech.vent')),
                ('orderNumber', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Irktech.order')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзины',
            },
        ),
    ]
