# Generated by Django 5.2.1 on 2025-05-27 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Irktech', '0004_order_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='amount',
        ),
    ]
