# Generated by Django 5.2.1 on 2025-05-27 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Irktech', '0005_remove_order_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='quantity',
            field=models.TextField(null=True, verbose_name='Количество'),
        ),
    ]
